#!/usr/bin/php
<?php

// Framework initialization and config loading.
require_once(__DIR__ . '/bootstrap.php');

// Executes the current console command.
\Aleph\Console\Controller::getInstance()->run();