<?php

return ['debugging' => true,
        'logging' => true,
        'templateDebug' => 'lib/tpl/debug.tpl',
        'cache' => ['type' => 'file',
                    'directory' => 'cache',
                    'gcProbability' => 33.333],
        'dirs' => ['application' => 'app',
                   'framework' => 'lib',
                   'logs' => 'app/tmp/logs',
                   'cache' => 'app/tmp/cache',
                   'temp' => 'app/tmp/null',
                   'ar' => 'app/core/model/ar',
                   'orm' => 'app/core/model/orm',
                   'js' => 'app/inc/js',
                   'css' => 'app/inc/css',
                   'tpl' => 'app/inc/tpl',
                   'elements' => 'app/inc/tpl/elements'],
        'db' => ['logging' => true,
                 'log' => 'app/tmp/sql.log',
                 'cacheExpire' => 0,
                 'cacheGroup' => '--db'],
        'ar' => ['cacheExpire' => -1,
                 'cacheGroup' => '--ar']];