<?php

return array('debugging' => 1,
             'logging' => 1,
             'templateDebug' => 'lib/tpl/debug.tpl',
             'cache' => array('gcProbability' => 33.333,
                              'cache' => 'file',
                              'directory' => 'cache'),
             'dirs' => array('logs' => 'app/logs',
                             'cache' => 'app/cache',
                             'temp' => 'app/temp',
                             'ar' => 'app/core/model/ar',
                             'orm' => 'app/core/model/orm'),
             'pom' => array('pageTemplateCacheEnable' => 1),
             'orm' => array('arDirectory' => 'ar',
                            'arTemplate' => 'lib/tpl/ar.tpl',
                            'ormDirectory' => 'orm',
                            'ormTemplate' => 'lib/tpl/orm.tpl'),
             'db' => array('dsn' => 'mysql:dbname=test;host=127.0.0.1',
                           'username' => '',
                           'password' => ''));